---
name: Searching for secrets

on:
  workflow_call:

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: TruffleHog | Install
        uses: supplypike/setup-bin@v3
        with:
          uri: 'https://github.com/trufflesecurity/trufflehog/releases/download/v3.90.6/trufflehog_3.90.6_linux_amd64.tar.gz'
          name: 'trufflehog'
          version: '3.90.6'

      - name: TruffleHog | Run
        run: trufflehog git file://./ --fail --debug --results=verified

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: "{workflow} has {status_message}"
          footer: "Linked Repo <{repo_url}|{repo}> | <{run_url}|View Workflow Run>"
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
        env:
          # need grant the repository access to the organization secret https://github.com/organizations/anyproto/settings/secrets/actions/SLACK_WEBHOOK_URL_ALERTS
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_ALERTS }}
